[package]
name = "launchpad-snake"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
launchy = { git = "https://github.com/Antony1060/launchy" }
anyhow = "1.0.79"
lazy_static = "1.4.0"
rand = "0.8.5"